import Link from "next/link";
import { IconScale } from "@tabler/icons-react";

export const metadata = {
  title: "Terms and Conditions — Octopus",
  description: "Terms and conditions for using the Octopus platform.",
};

export default function TermsPage() {
  return (
    <article className="max-w-3xl">
      <div className="mb-8">
        <div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-[#555]">
          <IconScale className="size-4" />
          Legal
        </div>
        <h1 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
          Terms and Conditions
        </h1>
        <p className="mt-3 text-sm text-[#555]">Last updated: March 2026</p>
      </div>

      <Section title="1. Acceptance of Terms">
        <P>
          By accessing or using Octopus (&quot;the Service&quot;), you agree
          to be bound by these Terms and Conditions. If you do not agree to
          these terms, please do not use the Service.
        </P>
      </Section>

      <Section title="2. Description of Service">
        <P>
          Octopus is an open source, AI-powered code review platform that
          analyzes pull requests, creates code embeddings, and provides
          automated review feedback. The Service is available as a
          cloud-hosted platform and as a self-hosted open source application.
        </P>
      </Section>

      <Section title="3. Accounts and Organizations">
        <P>
          You must create an account to use the cloud-hosted Service. You are
          responsible for maintaining the security of your account credentials
          and for all activities that occur under your account.
        </P>
        <P>
          Organizations are shared workspaces. Organization administrators are
          responsible for managing members and repository access within their
          organization.
        </P>
      </Section>

      <Section title="4. Your Code and Data">
        <P>
          You retain all ownership rights to your code. By connecting a
          repository to Octopus, you grant us a limited, non-exclusive license
          to access, process, and analyze your code solely for the purpose of
          providing the Service (code reviews, embeddings, and analysis).
        </P>
        <P>
          We do not claim any ownership over your code, review results, or
          generated content. You may disconnect repositories and delete your
          data at any time.
        </P>
      </Section>

      <Section title="5. AI-Generated Content">
        <P>
          Code reviews and analysis generated by Octopus are produced by
          third-party AI models (Anthropic Claude, OpenAI). While we strive
          for accuracy, AI-generated reviews are suggestions and should not be
          treated as definitive assessments.
        </P>
        <P>
          You are responsible for reviewing and validating all AI-generated
          feedback before acting on it. Octopus is not a substitute for human
          code review on critical systems.
        </P>
      </Section>

      <Section title="6. Acceptable Use">
        <P>You agree not to:</P>
        <UL>
          <li>Use the Service to process code you do not have rights to</li>
          <li>Attempt to reverse-engineer or extract AI model weights or proprietary algorithms</li>
          <li>Abuse API rate limits or attempt to circumvent usage restrictions</li>
          <li>Use the Service for any illegal purpose</li>
          <li>Interfere with the operation of the Service or other users&apos; access</li>
        </UL>
      </Section>

      <Section title="7. Usage Limits and Billing">
        <P>
          The Service includes usage-based limits on AI operations.
          Organizations may configure spend limits to control costs. If your
          organization exceeds its credit balance or spend limit, AI-powered
          features may be temporarily restricted.
        </P>
        <P>
          Payments are processed through Stripe. All fees are non-refundable
          unless otherwise stated.
        </P>
      </Section>

      <Section title="8. Open Source License">
        <P>
          The Octopus source code is licensed under the MIT License. You are
          free to use, modify, and distribute the software in accordance with
          that license. These Terms apply specifically to the cloud-hosted
          Service.
        </P>
      </Section>

      <Section title="9. Availability and Warranty">
        <P>
          The Service is provided &quot;as is&quot; and &quot;as
          available&quot; without warranties of any kind, either express or
          implied. We do not guarantee uninterrupted access to the Service.
        </P>
        <P>
          We may modify, suspend, or discontinue the Service at any time with
          reasonable notice. Since Octopus is open source, you can always
          self-host the application independently.
        </P>
      </Section>

      <Section title="10. Limitation of Liability">
        <P>
          To the maximum extent permitted by applicable law, Octopus and its
          developer shall not be liable for any indirect, incidental, special,
          consequential, or punitive damages arising out of or relating to
          your use of the Service.
        </P>
        <P>
          This includes, but is not limited to, damages arising from
          AI-generated review suggestions, missed bugs, or any actions taken
          based on the Service&apos;s output.
        </P>
      </Section>

      <Section title="11. Termination">
        <P>
          You may terminate your account at any time by deleting your account
          through the settings page. We may terminate or suspend your access
          if you violate these Terms.
        </P>
        <P>
          Upon termination, your data will be handled in accordance with our{" "}
          <Link
            href="/docs/privacy"
            className="text-white underline decoration-white/30 underline-offset-2 transition-colors hover:decoration-white"
          >
            Privacy Policy
          </Link>
          .
        </P>
      </Section>

      <Section title="12. Changes to Terms">
        <P>
          We may update these Terms from time to time. Changes will be posted
          on this page with an updated revision date. Continued use of the
          Service after changes constitutes acceptance of the updated Terms.
        </P>
      </Section>

      <Section title="13. Contact">
        <P>
          For questions about these Terms, please open an issue on our{" "}
          <a
            href="https://github.com/octopusreview"
            target="_blank"
            rel="noopener noreferrer"
            className="text-white underline decoration-white/30 underline-offset-2 transition-colors hover:decoration-white"
          >
            GitHub repository
          </a>
          .
        </P>
      </Section>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="mb-3 text-lg font-semibold text-white">{title}</h2>
      {children}
    </section>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="mb-3 text-sm leading-relaxed text-[#888]">{children}</p>;
}

function UL({ children }: { children: React.ReactNode }) {
  return <ul className="mb-3 list-inside list-disc space-y-1.5 text-sm text-[#888]">{children}</ul>;
}
