import Link from "@/components/link";
import { IconBook2 } from "@tabler/icons-react";

export const metadata = {
  title: "Glossary — Octopus Docs",
  description:
    "Quick reference for embeddings, vector search, severity levels, BYO keys, and every other technical term used across Octopus. Scan or search in seconds.",
  alternates: {
    canonical: "https://octopus-review.ai/docs/glossary",
  },
};

const glossary: { term: string; definition: string }[] = [
  {
    term: "BYO Keys (Bring Your Own Keys)",
    definition:
      "A configuration option that lets you use your own Anthropic or OpenAI API keys. AI token usage is billed directly to your provider account instead of consuming Octopus credits.",
  },
  {
    term: "Codebase Indexing",
    definition:
      "The process of cloning a repository, splitting its files into overlapping text chunks, generating vector embeddings for each chunk, and storing them in Qdrant. This enables fast, semantic search over your code during reviews and chat.",
  },
  {
    term: "Context Window",
    definition:
      "The maximum amount of text an LLM can process in a single request. Octopus uses vector search to select the most relevant code chunks so that reviews fit within the model's context window.",
  },
  {
    term: "Credits",
    definition:
      "The billing unit in Octopus. Each review, indexing operation, and chat message consumes credits based on token usage. Organizations receive free credits to get started and can purchase more or use BYO keys.",
  },
  {
    term: "Diff",
    definition:
      "The set of changes between two versions of code — typically the difference between a pull request branch and its base branch. Octopus fetches the diff to understand exactly what changed in a PR.",
  },
  {
    term: "Embeddings",
    definition:
      "Numerical vector representations of text generated by an AI model (default: OpenAI text-embedding-3-large). Embeddings capture semantic meaning, allowing Octopus to find code that is conceptually related to a query even if the exact words differ.",
  },
  {
    term: "Knowledge Base",
    definition:
      "A collection of documents you upload to Octopus — coding standards, architecture docs, style guides — that the AI references during reviews. This helps Octopus give feedback consistent with your team's specific conventions.",
  },
  {
    term: "LLM (Large Language Model)",
    definition:
      "An AI model trained on large amounts of text, such as Anthropic Claude or OpenAI GPT. Octopus sends code context and diffs to an LLM, which performs the actual analysis and generates review findings.",
  },
  {
    term: ".octopusignore",
    definition:
      "A configuration file placed at the root of your repository (same syntax as .gitignore) that tells Octopus which files and directories to skip during indexing and review — e.g., build outputs, vendor code, or generated files.",
  },
  {
    term: "Qdrant",
    definition:
      "An open-source vector database that Octopus uses to store and search code embeddings. It enables fast similarity search so the AI can retrieve the most relevant code chunks when reviewing a pull request or answering a chat question.",
  },
  {
    term: "Reranking",
    definition:
      "A second-pass relevance scoring step (using Cohere Rerank) applied after the initial vector search. It re-orders retrieved code chunks by how well they match the query, improving the quality of context sent to the LLM.",
  },
  {
    term: "Severity Levels",
    definition:
      "A rating system Octopus assigns to each review finding: 🔴 Critical (likely bug or security issue), 🟠 Major (significant concern), 🟡 Minor (style or minor issue), 🔵 Suggestion (improvement idea), 💡 Tip (informational note). Helps teams prioritize what to fix first.",
  },
  {
    term: "Spend Limit",
    definition:
      "A configurable monthly budget cap per organization. Octopus checks the limit before every expensive operation (review, indexing, chat) and stops processing if the organization is over budget — preventing surprise bills.",
  },
  {
    term: "Vector Search",
    definition:
      "A search technique that finds items by semantic similarity rather than exact keyword matching. Octopus converts a query into an embedding and finds the code chunks with the closest vectors in Qdrant, surfacing conceptually related code.",
  },
  {
    term: "Webhook",
    definition:
      "An HTTP callback sent by GitHub or Bitbucket to Octopus when an event occurs — typically a pull request being opened or updated. This is how Octopus knows when to start a review automatically.",
  },
];

export default function GlossaryPage() {
  return (
    <article className="max-w-3xl">
      <div className="mb-10">
        <div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-[#555]">
          <IconBook2 className="size-4" />
          Glossary
        </div>
        <h1 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
          Glossary
        </h1>
        <p className="mt-3 text-lg text-[#888]">
          Definitions for technical terms used throughout Octopus.
        </p>
      </div>

      <dl className="space-y-6">
        {glossary.map((item) => (
          <div
            key={item.term}
            id={item.term
              .toLowerCase()
              .replace(/[^a-z0-9]+/g, "-")
              .replace(/(^-|-$)/g, "")}
            className="scroll-mt-20 rounded-xl border border-white/[0.06] px-5 py-4 transition-colors hover:border-white/[0.12]"
          >
            <dt className="text-sm font-semibold text-white">{item.term}</dt>
            <dd className="mt-2 text-sm leading-relaxed text-[#888]">
              {item.definition}
            </dd>
          </div>
        ))}
      </dl>

      <div className="mt-12 rounded-xl border border-white/[0.06] bg-white/[0.02] px-6 py-5 text-center">
        <p className="text-sm text-[#888]">
          Have a question not covered here?{" "}
          <Link
            href="/docs/faq"
            className="text-white underline decoration-white/30 underline-offset-2 hover:decoration-white"
          >
            Check the FAQ
          </Link>{" "}
          or{" "}
          <a
            href="https://github.com/octopusreview"
            target="_blank"
            rel="noopener noreferrer"
            className="text-white underline decoration-white/30 underline-offset-2 hover:decoration-white"
          >
            open an issue on GitHub
          </a>
          .
        </p>
      </div>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "DefinedTermSet",
            name: "Octopus Glossary",
            description:
              "Definitions for technical terms used in the Octopus AI code review tool.",
            hasDefinedTerm: glossary.map((item) => ({
              "@type": "DefinedTerm",
              name: item.term,
              description: item.definition,
            })),
          }),
        }}
      />
    </article>
  );
}
